os: linux
dist: bionic
language: python
arch: amd64
addons:
  apt:
    update: true
install:
  - ./deps.sh --yes
  - pip install coverage
  - ./setup.py install
script: ./setup.py test
cache: pip
jobs:
  include:
   - stage: test
     dist: bionic
     python: 3.6
   - stage: test
     dist: bionic
     python: 3.7
   - stage: test
     dist: bionic
     python: 3.8
   - stage: test
     dist: bionic
     python: 3.9
   - stage: test
     dist: focal
     python: 3.6
   - stage: test
     dist: focal
     python: 3.7
   - stage: test
     dist: focal
     python: 3.8
   - stage: test
     dist: focal
     python: 3.9
   - stage: test
     services: docker
     install: 
       - docker build .
