dist:
  - bionic
  - focal
addons:
  apt:
    update: true
language: python
arch: 
 - amd64
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
install:
 - ./deps.sh --yes
 - pip install coverage
 - ./setup.py install
script: ./setup.py test
cache: pip
